#!/bin/bash

STYLE=java

function usage {
	echo "usage:"
	echo "    elml valider leçon ... - pour vérifier la syntaxe du fichier de la leçon"
	echo "    elml pdf     leçon ... - pour le PDF de la leçon"
	echo "    elml html    leçon ... - pour la version HTML (avec menu)"
	echo "    elml scorm   leçon ... - pour le scorm de la leçon (sans menu)"
	echo "    elml all     leçon ... - pour le PDF + HTML + scorm de la leçon"
	echo "    elml updateProfs  prof1 prof2 ... - Met à jour les profs de toutes les leçons"
}

function valider() {
	for LESSON in $LESSONS;
	do
		echo "=== $LESSON ==="
		valider1 $LESSON
	done
}

function valider1() {
	LESSON=$1
	xmllint --noout --schema _config/validate.xsd $LESSON/fr/text/$LESSON.xml
}

function pdf() {
	for LESSON in $LESSONS;
	do
		echo "=== $LESSON ==="
		pdf1 $LESSON
	done
}

function pdf1() {
	java -cp /usr/local/saxon/saxon9he.jar net.sf.saxon.Transform -t -s:$LESSON/fr/text/$LESSON.xml -xsl:_templates/$STYLE/latex.xsl
	if [[ $? == 0 ]]; then
		OLD=`pwd`
		cd $LESSON/fr/latex
		pdflatex $LESSON.tex
		cp $LESSON.pdf ../../../dist
		mv $LESSON.pdf ../text
		cd $OLD
	fi
}

function html() {
	for LESSON in $LESSONS;
	do
		echo "=== $LESSON ==="
		html1 $LESSON
	done
}

function html1() {
	java -cp /usr/local/saxon/saxon9he.jar net.sf.saxon.Transform -t -s:$LESSON/fr/text/$LESSON.xml -xsl:_templates/$STYLE/online.xsl
	ln -sf ../$LESSON/fr/html/index.html dist/$LESSON.html
	rm imsmanifest.xml sitemap.xml
}

function scorm() {
	for LESSON in $LESSONS;
	do
		echo "=== $LESSON ==="
		scorm1 $LESSON
	done
}

function scorm1() {
	sed -i -e "s|<use_navigation>yes</use_navigation>|<use_navigation>no</use_navigation>|" _config/config.xml
	java -cp /usr/local/saxon/saxon9he.jar net.sf.saxon.Transform -t -s:$LESSON/fr/text/$LESSON.xml -xsl:_templates/$STYLE/online.xsl
	zip -qr dist/$LESSON.zip imsmanifest.xml sitemap.xml $LESSON _templates/java
	rm imsmanifest.xml sitemap.xml
	sed -i -e "s|<use_navigation>no</use_navigation>|<use_navigation>yes</use_navigation>|" _config/config.xml
}

function all() {
	for LESSON in $LESSONS;
	do
		echo "=== $LESSON ==="
		scorm1 $LESSON
		html1 $LESSON
		pdf1 $LESSON
	done
}

function updateProfs() {
	PROFS=$LESSONS;
	sed -i -e "/<person.*>/d;" TD*/fr/text/TD*.xml;
	PERSONS=""
	for PROF in $PROFS
	do
		PERSONS="$PERSONS <person name=\"$PROF\" \/> "
	done
	sed -i -e "/<\/contribute>/ i $PERSONS" TD*/fr/text/TD*.xml;
}

if [[ $#<2 ]]; then usage; exit 1; fi
LESSONS=${@:2}

case $1 in
    valider ) valider ;;
    pdf ) pdf ;;
    html ) html ;;
    scorm ) scorm ;;
    all ) all ;;
    updateProfs ) updateProfs ;;
    * ) usage ;;
esac


